version: "2.4"

networks:
  image-db-net:
    external:
      name: image-db-net
  traefik_web:
    external:
      name: traefik_web

volumes:
  # Webroot
  labdesign-webroot-bind:
    driver: local
    driver_opts:
      type: none
      device: ${WEBROOT?You need to specify env WEBROOT, e.g. WEBROOT=/home/anders/projekt/labdesign/webserver}
      o: bind
  # this is microimages
  labdb-files-bind:
    driver: local
    driver_opts:
      type: none
      device: ${SHARE_LABDB?You need to specify env SHARE_LABDB, e.g. SHARE_LABDB=/share/data/labdb}
      o: bind

services:
  labdesignweb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: labdesign
    ports:
      - 8094:8080
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_web"
      - "traefik.port=8094"
      - "traefik.http.routers.labdesignweb.rule=Host(`${TRAEFIK_FRONTEND_URL?You need to specify env TRAEFIK_FRONTEND_URL, e.g. TRAEFIK_FRONTEND_URL=name.my-domain.com}`)"
      - "traefik.http.routers.labdesignweb.entrypoints=websecure"
      - "traefik.http.routers.labdesignweb.tls.certresolver=myresolver"
      # - traefik.frontend.auth.basic=${TRAEFIK_BASIC_AUTH? You need to specify env TRAEFIK_BASIC_AUTH, e.g. TRAEFIK_BASIC_AUTH=username:$blablsbskjfhbsjhslkfsjlkdslkjf/kljsd}


    networks:
      - image-db-net
      - traefik_web
    volumes:
      - labdesign-webroot-bind:/app
      - labdb-files-bind:/share/data/labdb

