version: "3.5"

networks:
  labdesign-net:
    external:
      name: labdesign-net
  traefik_web:
    external:
      name: traefik_web

volumes:
  # Webroot
  webroot-bind:
    driver: local
    driver_opts:
      type: none
      device: ${WEBROOT?You need to specify env WEBROOT, e.g. WEBROOT=/home/anders/projekt/labdesign/webserver}
      o: bind

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: labdesign
    ports:
      - 8095:8080
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_web"
      - "traefik.port=8095"
      - "traefik.http.routers.web.rule=Host(`${TRAEFIK_FRONTEND_URL?You need to specify env TRAEFIK_FRONTEND_URL, e.g. TRAEFIK_FRONTEND_URL=name.my-domain.com}`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      # - traefik.frontend.auth.basic=${TRAEFIK_BASIC_AUTH? You need to specify env TRAEFIK_BASIC_AUTH, e.g. TRAEFIK_BASIC_AUTH=username:$blablsbskjfhbsjhslkfsjlkdslkjf/kljsd}


    networks:
      - labdesign-net
      - traefik_web
    volumes:
      - webroot-bind:/app