version: "3.5"

networks:
  labdesign-net:
    driver: bridge
    name: labdesign-net
  traefik_web:
    external:
      name: traefik_web

volumes:
  db-labdesign-pg:

services:

  labdesigndb:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD?You need to specify env DB_PASSWORD, e.g. DB_PASSWORD=name.my-domain.com}
    volumes:
      - db-labdesign-pg:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - labdesign-net

  labdesidnadminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    networks:
      - labdesign-net
      - traefik_web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_web"
      - "traefik.port=8088"
      - "traefik.http.routers.labdesidnadminer.rule=Host(`${TRAEFIK_FRONTEND_URL?You need to specify env TRAEFIK_FRONTEND_URL, e.g. TRAEFIK_FRONTEND_URL=name.my-domain.com}`)"
      - "traefik.http.routers.labdesidnadminer.entrypoints=websecure"
      - "traefik.http.routers.labdesidnadminer.tls.certresolver=myresolver"
